### ISSUE TITLE
Support cucumber > 2.1.x

### ISSUE THREAD

**Issue by bmulholland** [circleci/cucumber-formatter#4]
I'm currently getting this on CircleCI:

```
bundle exec cucumber --format CircleCICucumberFormatter::CircleCIJson --out /tmp/circle-junit.BfSKvIL/cucumber/cucumber.cucumber
cannot load such file -- cucumber/formatter/gherkin_formatter_adapter (LoadError)
```

This is happening with cucumber-ruby 2.3.2, which is now supported by cucumber-rails 1.4.3. gherkin_formatter_adapter.rb was removed between cucumber-ruby 2.0.0 and 2.1.0. https://github.com/cucumber/cucumber-ruby/commits/v2.1.0/lib/cucumber/formatter/gherkin_formatter_adapter.rb

**Comment by lpenaflor** [comment]
This may help you - https://github.com/circleci/cucumber-formatter/pull/6

**Comment by zzak** [comment]
Hello!

I just merged that patch.. so sorry for the delay :bow:

Please let me know if this fixes your issue!
